# Generated by Django 5.0 on 2024-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='IMDb ID'),
        ),
    ]
