# Generated by Django 5.0 on 2024-04-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_category_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='type',
        ),
    ]
