# Generated by Django 5.0 on 2024-04-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0006_alter_actor_movies'),
        ('main', '0006_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.director', verbose_name='کارگردان'),
        ),
    ]
