# Generated by Django 5.0 on 2024-05-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='category',
        ),
    ]
