# Generated by Django 5.0 on 2024-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_actor_tmdb_id'),
        ('main', '0004_rename_category_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='main.movie'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
