# Generated by Django 5.0 on 2024-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_actor_movies_alter_actor_name_alter_actor_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='director/'),
        ),
    ]
