# Generated by Django 5.0 on 2024-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0005_actor_image_url'),
        ('main', '0006_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='actors', to='main.movie'),
        ),
    ]
