# Generated by Django 5.0 on 2024-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0007_director_tmdb_id'),
        ('main', '0008_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image_url',
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='directors', to='main.movie', verbose_name='فیلم\u200cهای کارگردان'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='actors', to='main.movie', verbose_name='فیلم\u200cهای کارگردان'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='نام بازیگر'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='poster',
            field=models.URLField(blank=True, null=True, verbose_name='تصویر بازیگر'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ایدی بازیگر'),
        ),
        migrations.AlterField(
            model_name='director',
            name='poster',
            field=models.URLField(blank=True, null=True, verbose_name='تصویر کارگردان'),
        ),
        migrations.AlterField(
            model_name='director',
            name='tmdb_id',
            field=models.IntegerField(unique=True, verbose_name='شناسه TMDB کارگردان'),
        ),
    ]
