# Generated by Django 5.0 on 2024-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0008_remove_actor_image_url_director_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد فیلم\u200cها'),
        ),
        migrations.AddField(
            model_name='actor',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معروفیت'),
        ),
        migrations.AddField(
            model_name='director',
            name='movie_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد فیلم\u200cها'),
        ),
        migrations.AddField(
            model_name='director',
            name='popularity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معروفیت'),
        ),
    ]
